"""Run valgrind's arm64 instruction tests (none/tests/arm64) in the simulator
generated by lira-simgen-lib.

Each test executes single instructions from inline asm and prints the result
registers and NZCV. The reference is either valgrind's .stdout.exp (recorded on
hardware) or the same source run natively on an AArch64 host.

Needs a valgrind checkout ($VALGRIND_SRC, default ../valgrind next to LIRA);
only none/tests/arm64 is used:

    git clone --depth 1 --filter=blob:none --sparse https://sourceware.org/git/valgrind.git
    git -C valgrind sparse-checkout set none/tests/arm64

The sources are GPL-2 and are not copied here. The guest build uses the libc in
valgrind/, the simulator runs the integer subset only (no SIMD&FP, LSE or
exclusives).
"""
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

import pytest

from .test_programs import CC, GUEST_FLAGS, HOST_CC, LD, SIM

HERE = Path(__file__).resolve().parent
RT = HERE / 'valgrind'
VALGRIND = Path(os.environ.get('VALGRIND_SRC', HERE.parents[3] / 'valgrind'))
TESTS = VALGRIND / 'none' / 'tests' / 'arm64'

AARCH64_HOST = platform.machine() in ('arm64', 'aarch64')

pytestmark = [
    pytest.mark.skipif(not SIM.exists(), reason=f'{SIM} not built'),
    pytest.mark.skipif(CC is None or LD is None, reason='no aarch64 clang / ld.lld'),
    pytest.mark.skipif(not TESTS.is_dir(), reason=f'no valgrind checkout at {VALGRIND} (set $VALGRIND_SRC)'),
]


def cast_operands(src: str) -> str:
    """The TESTINST macros pass int literals to "r" operands used as X registers,
    whose upper half is then undefined; make them 64-bit."""
    return re.sub(r'"r" \((R[A-Z]+val)\)', r'"r" ((ULong)(\1))', src)


# SIMD&FP registers and instructions the simulator subset does not have.
_UNSUPPORTED = re.compile(r'\b[vqdsbh]\d+\b|\b(ld|st)[1-4]r?\b|\b(ldar|stlr|ldx|stx|ldaxr|stlxr)[bhp]?\b')
_CASE = re.compile(r'^\s*(MEM_TEST|TESTINST\w*)\s*\(\s*("(?:[^"\\]|\\.)*")')


def integer_only(src: str) -> str:
    """memory_test.c without SIMD&FP: drop the q17-q20 transfer from MEM_TEST
    (their xor lines stay 0 for integer instructions) and every case outside
    the simulator subset."""
    out = []
    lines = iter(src.split('\n'))
    for line in lines:
        if re.search(r'"(ldr|str) q(17|18|19|20),', line):
            continue
        line = line.replace('"v17", "v18", "v19", "v20", ', '')
        # AREA_MID rounds into `area` by address; pin its alignment so the
        # data read does not depend on the stack layout.
        line = line.replace('unsigned char area[512];', 'unsigned char area[512] __attribute__((aligned(16)));')
        m = _CASE.match(line)
        if not m:
            out.append(line)
            continue
        case = [line]
        while not re.search(r'\)\s*;?\s*$', case[-1]):
            case.append(next(lines))
        if not _UNSUPPORTED.search(m.group(2)):
            out.extend(case)
    return '\n'.join(out)


_SEMI = '''
static const char *semi(const char *s) {
  static char buf[512];
  int i = 0;
  for (; s[i] && i < 511; i++)
    buf[i] = s[i] == '\\n' ? ';' : s[i];
  buf[i] = 0;
  return buf;
}
'''


def darwin(src: str) -> str:
    """Darwin's assembler treats ';' as a comment: separate the asm statements
    with newlines and print the instruction text with ';' restored."""
    src = re.sub(r'"(?:[^"\\\n]|\\.)*"', lambda m: m.group(0).replace(';', '\\n'), src)
    src = src.replace('      instruction, out,', '      semi(instruction), out,')
    src = src.replace('         INSN, (Long)AREG1OFF', '         semi(INSN), (Long)AREG1OFF')
    end = src.index('\n', src.index('#include <assert.h>')) + 1
    return src[:end] + _SEMI + src[end:]


def build_guest(src: Path, elf: Path, *flags):
    subprocess.run([CC, '-O0', *GUEST_FLAGS, '-march=armv8-a+crc', '-fno-builtin', '-nostdlibinc',
                    f'-I{RT / "include"}', '-w', f'--ld-path={LD}', *flags, '-o', elf, src, RT / 'rt.c'],
                   check=True)


def run_guest(elf: Path) -> str:
    p = subprocess.run([SIM, '--propagate-exit', '-q', elf], capture_output=True, text=True, timeout=600)
    assert p.stderr == '', p.stderr
    assert p.returncode == 0
    return ''.join(l for l in p.stdout.splitlines(keepends=True) if not l.startswith('Exiting with code'))


def run_host(src: Path, exe: Path, *flags) -> str:
    if sys.platform == 'darwin':
        darwin_src = src.with_name(f'{src.stem}_darwin.c')
        darwin_src.write_text(darwin(src.read_text()))
        src = darwin_src
    subprocess.run([*HOST_CC, '-O0', '-w', f'-I{RT / "host"}', *flags, '-o', exe, src], check=True)
    p = subprocess.run([exe], capture_output=True, text=True, timeout=600)
    assert p.returncode == 0
    return p.stdout


@pytest.mark.parametrize('prog, flags', [
    ('integer', ['-DTEST_BFM=0']),  # as in valgrind's Makefile.am
    ('crc32', []),
])
def test_expected(prog, flags, tmp_path):
    """Compare with valgrind's expected output, recorded on hardware."""
    src = tmp_path / f'{prog}.c'
    src.write_text(cast_operands((TESTS / f'{prog}.c').read_text()))
    build_guest(src, tmp_path / f'{prog}.elf', *flags)
    assert run_guest(tmp_path / f'{prog}.elf') == (TESTS / f'{prog}.stdout.exp').read_text()


@pytest.mark.skipif(not AARCH64_HOST, reason='reference output needs an AArch64 host')
@pytest.mark.parametrize('prog, transform, flags', [
    ('integer', cast_operands, ['-DTEST_BFM=1']),  # + SBFM/UBFM/BFM, no .stdout.exp
    ('memory_test', lambda s: cast_operands(integer_only(s)), []),
])
def test_host(prog, transform, flags, tmp_path):
    """Compare with the same source run natively."""
    src = tmp_path / f'{prog}.c'
    src.write_text(transform((TESTS / f'{prog}.c').read_text()))
    build_guest(src, tmp_path / f'{prog}.elf', *flags)
    assert run_guest(tmp_path / f'{prog}.elf') == run_host(src, tmp_path / prog, *flags)
