"""Verify the simulator generated by lira-simgen-lib from aarch64.yaml.

Uses the single-instruction C API library built by
    cmake --build <build> --target a64-capi      (ARCH_TARGET=AArch64)
located via $LIRA_A64_CAPI (default: ../lira-simgen-lib/build/a64/...).

* decoder: every sampled valid word decodes to its own opcode, and words that
  no encoding accepts are rejected;
* generated C++ vs. the host CPU (same cases as test_semantics_hw);
* generated C++ vs. the reference interpreter on all encodings with fully
  random fields (register 31 = SP/XZR, branches, literal loads included).
"""
import ctypes
import os
import random
from pathlib import Path

import pytest

from .conftest import sample_operands
from .test_semantics_hw import (MEM_BASE_OFF, MEM_SIZE, STATES_PER_CASE, _random_state,
                                cases, interp_step)

DEFAULT = Path(__file__).resolve().parents[4] / 'lira-simgen-lib' / 'build' / 'a64' / \
    'interpreter' / 'liba64-capi.dylib'
CAPI = Path(os.environ.get('LIRA_A64_CAPI', DEFAULT))

pytestmark = pytest.mark.skipif(not CAPI.exists(), reason=f'{CAPI} not built')

U64P = ctypes.POINTER(ctypes.c_uint64)


@pytest.fixture(scope='module')
def capi():
    lib = ctypes.CDLL(str(CAPI))
    lib.lira_a64_exec.argtypes = [ctypes.c_uint32, U64P, U64P, U64P]
    lib.lira_a64_decode.argtypes = [ctypes.c_uint32]
    return lib


def sim_step(capi, word, x, nzcv, pc):
    xs = (ctypes.c_uint64 * 32)(*x)
    f = ctypes.c_uint64(nzcv)
    p = ctypes.c_uint64(pc)
    assert capi.lira_a64_exec(word, xs, ctypes.byref(f), ctypes.byref(p)) == 0, hex(word)
    return list(xs), f.value, p.value


def test_decoder(arch, machine, capi):
    rng = random.Random(21)
    for idx, ins in enumerate(arch.instructions):
        for _ in range(30):
            word = machine.encode(ins, sample_operands(machine, ins, rng))
            assert capi.lira_a64_decode(word) == idx, (ins.name, hex(word))
    rejected = 0
    for _ in range(20000):
        word = rng.getrandbits(32)
        if not any(machine.valid_word(i, word) for i in arch.instructions):
            assert capi.lira_a64_decode(word) == -1, hex(word)
            rejected += 1
    assert rejected > 1000


def test_simgen_matches_hardware(arch, cases, capi):
    rng = random.Random(11)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for fn, ins, ops, word in cases:
        for _ in range(STATES_PER_CASE):
            regs, nzcv = _random_state(rng, ins, ops, base)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))
            ctypes.memmove(mem, init, MEM_SIZE)
            state = (ctypes.c_uint64 * 10)(*regs, nzcv, 0)
            fn(state)
            hw = (list(state[:8]), state[8] >> 28, bytes(mem))
            pc = state[9]
            ctypes.memmove(mem, init, MEM_SIZE)
            x, f, _ = sim_step(capi, word, regs + [0] * 24, nzcv >> 28, pc)
            got = (x[:8], f, bytes(mem))
            if got != hw:
                failures.append((ins.name, hex(word), [hex(r) for r in regs],
                                 'hw', [hex(r) for r in hw[0]], hw[1],
                                 'sim', [hex(r) for r in got[0]], got[1]))
                break
    assert not failures, '\n'.join(map(str, failures[:20])) + f'\n({len(failures)} failing)'


def _pick(machine, ins, rng):
    fixed = {}
    if '_ldst' in ins.name and 'Rm' in ins.operand_names:
        rn = rng.randrange(32)
        fixed['Rn'] = rn
        fixed['Rm'] = rng.choice([r for r in range(32) if r != rn])
    if 'imm12' in ins.operand_names and '_ldst' in ins.name:
        fixed['imm12'] = rng.randrange(256)          # scaled offset stays in the buffer
    if 'loadlit' in ins.name:
        fixed['imm19'] = rng.randrange(-512, 512) & ((1 << 19) - 1)
    return sample_operands(machine, ins, rng, fixed)


def test_simgen_matches_interpreter(arch, machine, capi):
    rng = random.Random(5)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for ins in arch.instructions:
        if ins.name.startswith('SVC_'):                 # effect defined by the runtime
            continue
        is_mem = '_ldst' in ins.name or 'loadlit' in ins.name
        for _ in range(40):
            ops = _pick(machine, ins, rng)
            word = machine.encode(ins, ops)
            names = dict(zip(ins.operand_names, ops))
            x = [rng.getrandbits(64) if rng.random() < 0.7 else rng.choice([0, 1, (1 << 64) - 1, 1 << 63])
                 for _ in range(32)]
            pc = base + MEM_BASE_OFF if is_mem else rng.getrandbits(62) << 2
            if is_mem:
                if 'Rn' in names:
                    x[names['Rn']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
                if 'Rm' in names and names['Rm'] != 31:
                    x[names['Rm']] = rng.randrange(256)
            nzcv = rng.getrandbits(4)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))

            ref = interp_step(arch, ins, word, x, nzcv, pc, base, init)
            ctypes.memmove(mem, init, MEM_SIZE)
            sx, sf, spc = sim_step(capi, word, x, nzcv, pc)
            got = (sx, sf, bytes(mem), spc)
            if got != (ref[0], ref[1], ref[2], ref[3]):
                diff = [f'x{i}: ref={ref[0][i]:#x} sim={sx[i]:#x}' for i in range(32) if ref[0][i] != sx[i]]
                failures.append((ins.name, hex(word), names, diff,
                                 f'nzcv ref={ref[1]} sim={sf}', f'pc ref={ref[3]:#x} sim={spc:#x}',
                                 'mem differs' if got[2] != ref[2] else ''))
                break
    assert not failures, '\n'.join(map(str, failures[:25])) + f'\n({len(failures)} failing)'
