"""Run valgrind's arm64 instruction tests (none/tests/arm64) in the simulator
generated by lira-simgen-lib.

Each test executes single instructions from inline asm and prints the result
registers and NZCV. The reference is either valgrind's .stdout.exp (recorded on
hardware) or the same source run natively on an AArch64 host.

Needs a valgrind checkout ($VALGRIND_SRC, default ../valgrind next to LIRA);
only none/tests/arm64 is used:

    git clone --depth 1 --filter=blob:none --sparse https://sourceware.org/git/valgrind.git
    git -C valgrind sparse-checkout set none/tests/arm64

The sources are GPL-2 and are not copied here. The guest build uses the libc in
valgrind/. Tests of features the simulator does not run yet are left out, and
memory_test keeps the cases whose instructions all decode in the description
the simulator was generated from (`supported_only`).
"""
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

import pytest

from .test_programs import CC, GUEST_FLAGS, HOST_CC, LD, SIM
from .test_simgen import SIM_YAML

HERE = Path(__file__).resolve().parent
RT = HERE / 'valgrind'
VALGRIND = Path(os.environ.get('VALGRIND_SRC', HERE.parents[3] / 'valgrind'))
TESTS = VALGRIND / 'none' / 'tests' / 'arm64'

AARCH64_HOST = platform.machine() in ('arm64', 'aarch64')

pytestmark = [
    pytest.mark.skipif(not SIM.exists(), reason=f'{SIM} not built'),
    pytest.mark.skipif(CC is None or LD is None, reason='no aarch64 clang / ld.lld'),
    pytest.mark.skipif(not TESTS.is_dir(), reason=f'no valgrind checkout at {VALGRIND} (set $VALGRIND_SRC)'),
]


def cast_operands(src: str) -> str:
    """The TESTINST macros pass int literals to "r" operands used as X registers,
    whose upper half is then undefined; make them 64-bit."""
    return re.sub(r'"r" \((R[A-Z]+val)\)', r'"r" ((ULong)(\1))', src)


MC_ATTRS = '+v8.9a,+fullfp16,+fp16fml,+aes,+sha2,+sha3,+sm4,+i8mm,+dotprod,+rdm,+crc,+lse'


def _byte(b: str) -> int:
    """A byte of llvm-mc's encoding; fixup bits (label references) read as 0."""
    b = b.strip()
    if b.startswith('0x'):
        return int(b, 16)
    return int(re.sub(r'[^01]', '0', b[2:] if b.startswith('0b') else '0'), 2)


def assemble(texts):
    """Encode each asm text (statements separated by ';' or newlines) with
    llvm-mc: the list of words per text, None where a statement is rejected."""
    mc = Path(CC).with_name('llvm-mc')
    lines, owner = [], []           # asm lines; the text each line belongs to
    for i, text in enumerate(texts):
        stmts = [st.strip() for st in re.split(r'[;\n]', text) if st.strip()]
        lines += [f'.ascii "@{i}"'] + stmts
        owner += [i] * (len(stmts) + 1)
    p = subprocess.run([mc, '-triple=aarch64', f'-mattr={MC_ATTRS}', '--show-encoding'],
                       input='\n'.join(lines), capture_output=True, text=True)
    bad = {owner[int(n) - 1] for n in re.findall(r'^<stdin>:(\d+):\d+: error', p.stderr, re.M)}
    words, cur = [[] for _ in texts], None
    for line in p.stdout.splitlines():
        if m := re.search(r'\.ascii\s+"@(\d+)"', line):
            cur = int(m.group(1))
        elif m := re.search(r'encoding: \[([^\]]*)\]', line):
            words[cur].append(int.from_bytes(bytes(map(_byte, m.group(1).split(','))), 'little'))
    return [None if i in bad else w for i, w in enumerate(words)]


_sim_decoder = None


def sim_decodes(word: int) -> bool:
    """The word decodes in the description the simulator was generated from."""
    global _sim_decoder
    if _sim_decoder is None:
        from python.lira.arch_ser_yaml import read_arch
        from .lira_interp import Machine
        arch = read_arch(SIM_YAML)
        _sim_decoder = Machine(arch), arch.instructions
    machine, insns = _sim_decoder
    return any(machine.valid_word(ins, word) for ins in insns)


def supported(texts):
    """For each asm text: every statement assembles and decodes in the simulator."""
    return [w is not None and all(map(sim_decodes, w)) for w in assemble(texts)]


_CASE = re.compile(r'^\s*(MEM_TEST|TESTINST\w*)\s*\(\s*("(?:[^"\\]|\\.)*")')


def supported_only(src: str) -> str:
    """memory_test.c with the cases the simulator runs."""
    lines = src.split('\n')
    cases, i = [], 0                # (first line, last line, asm text)
    while i < len(lines):
        m = _CASE.match(lines[i])
        if m:
            j = i
            while not re.search(r'\)\s*;?\s*$', lines[j]):
                j += 1
            cases.append((i, j, m.group(2)[1:-1]))
            i = j
        i += 1
    drop = set()
    for (first, last, _), ok in zip(cases, supported([c[2] for c in cases])):
        if not ok:
            drop.update(range(first, last + 1))
    out = []
    for n, line in enumerate(lines):
        if n in drop:
            continue
        # AREA_MID rounds into `area` by address; pin its alignment so the
        # data read does not depend on the stack layout.
        out.append(line.replace('unsigned char area[512];', 'unsigned char area[512] __attribute__((aligned(16)));'))
    return '\n'.join(out)


_SEMI = '''
static const char *semi(const char *s) {
  static char buf[512];
  int i = 0;
  for (; s[i] && i < 511; i++)
    buf[i] = s[i] == '\\n' ? ';' : s[i];
  buf[i] = 0;
  return buf;
}
'''


def darwin(src: str) -> str:
    """Darwin's assembler treats ';' as a comment: separate the asm statements
    with newlines and print the instruction text with ';' restored."""
    src = re.sub(r'"(?:[^"\\\n]|\\.)*"', lambda m: m.group(0).replace(';', '\\n'), src)
    src = src.replace('      instruction, out,', '      semi(instruction), out,')
    src = src.replace('         INSN, (Long)AREG1OFF', '         semi(INSN), (Long)AREG1OFF')
    end = src.index('\n', src.index('#include <assert.h>')) + 1
    return src[:end] + _SEMI + src[end:]


def build_guest(src: Path, elf: Path, *flags):
    # The tests' inline asm uses SIMD&FP registers; the compiler must not
    # (-mno-implicit-float instead of -mgeneral-regs-only).
    cflags = [f for f in GUEST_FLAGS if f != '-mgeneral-regs-only'] + ['-mno-implicit-float']
    subprocess.run([CC, '-O0', *cflags, '-march=armv8-a+crc', '-fno-builtin', '-nostdlibinc',
                    f'-I{RT / "include"}', '-w', f'--ld-path={LD}', *flags, '-o', elf, src, RT / 'rt.c'],
                   check=True)


def run_guest(elf: Path) -> str:
    p = subprocess.run([SIM, '--propagate-exit', '-q', elf], capture_output=True, text=True, timeout=600)
    assert p.stderr == '', p.stderr
    assert p.returncode == 0
    return ''.join(l for l in p.stdout.splitlines(keepends=True) if not l.startswith('Exiting with code'))


def run_host(src: Path, exe: Path, *flags) -> str:
    if sys.platform == 'darwin':
        darwin_src = src.with_name(f'{src.stem}_darwin.c')
        darwin_src.write_text(darwin(src.read_text()))
        src = darwin_src
    subprocess.run([*HOST_CC, '-O0', '-w', f'-I{RT / "host"}', *flags, '-o', exe, src], check=True)
    p = subprocess.run([exe], capture_output=True, text=True, timeout=600)
    assert p.returncode == 0
    return p.stdout


# program, expected output, flags (as in valgrind's Makefile.am)
@pytest.mark.parametrize('prog, expected, flags', [
    ('integer', 'integer', ['-DTEST_BFM=0']),
    ('crc32', 'crc32', []),
    ('atomics_v81', 'atomics_v81', ['-march=armv8.1-a']),
    ('ldxp_stxp', 'ldxp_stxp_basisimpl', []),
])
def test_expected(prog, expected, flags, tmp_path):
    """Compare with valgrind's expected output, recorded on hardware."""
    src = tmp_path / f'{prog}.c'
    src.write_text(cast_operands((TESTS / f'{prog}.c').read_text()))
    build_guest(src, tmp_path / f'{prog}.elf', *flags)
    assert run_guest(tmp_path / f'{prog}.elf') == (TESTS / f'{expected}.stdout.exp').read_text()


@pytest.mark.skipif(not AARCH64_HOST, reason='reference output needs an AArch64 host')
@pytest.mark.parametrize('prog, transform, flags', [
    ('integer', cast_operands, ['-DTEST_BFM=1']),  # + SBFM/UBFM/BFM, no .stdout.exp
    ('memory_test', lambda s: cast_operands(supported_only(s)), []),
])
def test_host(prog, transform, flags, tmp_path):
    """Compare with the same source run natively."""
    src = tmp_path / f'{prog}.c'
    src.write_text(transform((TESTS / f'{prog}.c').read_text()))
    build_guest(src, tmp_path / f'{prog}.elf', *flags)
    assert run_guest(tmp_path / f'{prog}.elf') == run_host(src, tmp_path / prog, *flags)
