"""Verify the simulator generated by lira-simgen-lib from aarch64.yaml.

Uses the single-instruction C API library built by
    cmake --build <build> --target a64-capi      (ARCH_TARGET=AArch64)
located via $LIRA_A64_CAPI (default: ../lira-simgen-lib/build/a64/...).

* decoder: every sampled valid word decodes to its own opcode, and words that
  no encoding accepts are rejected;
* generated C++ vs. the host CPU (same cases as test_semantics_hw);
* generated C++ vs. the reference interpreter on all encodings with fully
  random fields (register 31 = SP/XZR, branches, literal loads included).
"""
import ctypes
import os
import platform
import random
import sys
from pathlib import Path

import pytest

from .conftest import sample_operands
from .test_semantics_hw import (M64, MEM_BASE_OFF, MEM_SIZE, STATES_PER_CASE, Fault,
                                build_cases, diff_state, interp_step, random_state, random_v,
                                run_hw)

DEFAULT = Path(__file__).resolve().parents[4] / 'lira-simgen-lib' / 'build' / 'a64' / \
    'interpreter' / ('liba64-capi.dylib' if sys.platform == 'darwin' else 'liba64-capi.so')
CAPI = Path(os.environ.get('LIRA_A64_CAPI', DEFAULT))
# The description the simulator was generated from (may lag behind aarch64.yaml)
SIM_YAML = Path(os.environ.get('LIRA_A64_SIM_YAML',
                               DEFAULT.parents[3] / 'data' / 'AArch64' / 'aarch64.yaml'))

pytestmark = pytest.mark.skipif(not (CAPI.exists() and SIM_YAML.exists()),
                                reason=f'{CAPI} or {SIM_YAML} not found')

U64P = ctypes.POINTER(ctypes.c_uint64)


@pytest.fixture(scope='module')
def sim_arch():
    from python.lira.arch_ser_yaml import read_arch
    return read_arch(SIM_YAML)


@pytest.fixture(scope='module')
def sim_machine(sim_arch):
    from .lira_interp import Machine
    return Machine(sim_arch)


@pytest.fixture(scope='module')
def sim_cases(sim_arch, tmp_path_factory):
    """Hardware cases for the instructions of the simulated description."""
    return build_cases(sim_arch, tmp_path_factory.mktemp('hw'))


@pytest.fixture(scope='module')
def capi():
    lib = ctypes.CDLL(str(CAPI))
    lib.lira_a64_exec.argtypes = [ctypes.c_uint32, U64P, U64P, U64P, U64P, U64P, U64P]
    lib.lira_a64_decode.argtypes = [ctypes.c_uint32]
    return lib


SIM_FAULT = -2       # lira_a64_exec: runtime error (an Alignment or PAC fault)


def sim_exec(capi, word, st, pc):
    """Run one word in the generated simulator on state `st` (X and V with up to
    32 registers, NZCV, FPCR, FPSR): (rc, state with 32 X/V registers, pc)."""
    x = st['X'] + [0] * (32 - len(st['X']))
    v = st['V'] + [0] * (32 - len(st['V']))
    xs = (ctypes.c_uint64 * 32)(*x)
    vs = (ctypes.c_uint64 * 64)(*[w for r in v for w in (r & M64, r >> 64)])
    regs = [ctypes.c_uint64(r) for r in (st['NZCV'], st['FPCR'], st['FPSR'], pc)]
    rc = capi.lira_a64_exec(word, xs, vs, *map(ctypes.byref, regs))
    out = {'X': list(xs), 'V': [vs[2 * i] | vs[2 * i + 1] << 64 for i in range(32)],
           'NZCV': regs[0].value, 'FPCR': regs[1].value, 'FPSR': regs[2].value}
    return rc, out, regs[3].value


def sim_step(capi, word, st, pc):
    rc, out, pc = sim_exec(capi, word, st, pc)
    assert rc == 0, (hex(word), rc)
    return out, pc


def test_decoder(sim_arch, sim_machine, capi):
    rng = random.Random(21)
    arch, machine = sim_arch, sim_machine
    for idx, ins in enumerate(arch.instructions):
        for _ in range(30):
            word = machine.encode(ins, sample_operands(machine, ins, rng))
            assert capi.lira_a64_decode(word) == idx, (ins.name, hex(word))
    rejected = 0
    for _ in range(20000):
        word = rng.getrandbits(32)
        if not any(machine.valid_word(i, word) for i in arch.instructions):
            assert capi.lira_a64_decode(word) == -1, hex(word)
            rejected += 1
    assert rejected > 1000


@pytest.mark.skipif(platform.machine() not in ('arm64', 'aarch64'), reason='needs an AArch64 host')
def test_simgen_matches_hardware(sim_arch, sim_cases, capi):
    """X and V registers, NZCV, FPCR, FPSR and memory of the generated C++ vs. the host CPU."""
    rng = random.Random(11)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for fn, ins, ops, word in sim_cases:
        for _ in range(STATES_PER_CASE):
            st = random_state(rng, ins, ops, base)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))
            ctypes.memmove(mem, init, MEM_SIZE)
            hw, pc = run_hw(fn, st)
            hw_mem = bytes(mem)
            ctypes.memmove(mem, init, MEM_SIZE)
            sim, _ = sim_step(capi, word, st, pc)
            sim = dict(sim, X=sim['X'][:8], V=sim['V'][:8])
            if diff_state(hw, sim) or bytes(mem) != hw_mem:
                failures.append((ins.name, hex(word), 'hw vs sim:', diff_state(hw, sim),
                                 'mem differs' if bytes(mem) != hw_mem else ''))
                break
    assert not failures, '\n'.join(map(str, failures[:20])) + f'\n({len(failures)} failing)'


def _is_mem(ins):
    """Accesses memory: calls a mem_* environment function."""
    return any(st.kind in ('env', 'cond_env') and st.specifier.startswith('mem_')
               for st in ins.semantic.stmts) and not _is_mops(ins)


def _is_mops(ins):
    return ins.name.endswith(('_memcms', '_memcms_st')) or '_SET_' in ins.name


def _pick(machine, ins, rng):
    fixed = {}
    if _is_mops(ins):                                # distinct Rd, Rs, Rn below 31
        fixed.update(zip(('Rd', 'Rs', 'Rn'), rng.sample(range(31), 3)))
        return sample_operands(machine, ins, rng, fixed)
    if _is_mem(ins) and 'Rm' in ins.operand_names:
        rn = rng.randrange(32)
        fixed['Rn'] = rn
        fixed['Rm'] = rng.choice([r for r in range(32) if r != rn])
    if 'imm12' in ins.operand_names and _is_mem(ins):
        fixed['imm12'] = rng.randrange(64)           # scaled offset (up to x16) stays in the buffer
    if 'loadlit' in ins.name:
        fixed['imm19'] = rng.randrange(-512, 512) & ((1 << 19) - 1)
    try:
        return sample_operands(machine, ins, rng, fixed)
    except AssertionError:
        if fixed.get('Rm') != 31:                    # Rm = 31 selects another form (post-index)
            raise
        fixed['Rm'] = rng.choice([r for r in range(31) if r != fixed['Rn']])
        return sample_operands(machine, ins, rng, fixed)


def test_simgen_matches_interpreter(sim_arch, sim_machine, capi):
    arch, machine = sim_arch, sim_machine
    rng = random.Random(5)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for ins in arch.instructions:
        if ins.name.startswith('SVC_'):                 # effect defined by the runtime
            continue
        is_mem = _is_mem(ins)
        for _ in range(40):
            ops = _pick(machine, ins, rng)
            word = machine.encode(ins, ops)
            names = dict(zip(ins.operand_names, ops))
            x = [rng.getrandbits(64) if rng.random() < 0.7 else rng.choice([0, 1, (1 << 64) - 1, 1 << 63])
                 for _ in range(32)]
            v = [random_v(rng) for _ in range(32)]
            pc = base + MEM_BASE_OFF if is_mem else rng.getrandbits(62) << 2
            if ins.name.startswith('SYS_'):   # DC ZVA stays in the buffer
                x[names['Rt']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
            if _is_mops(ins):          # Rd, Rs addresses (or Rs data), Rn size
                x[names['Rd']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
                if ins.name.startswith('CPY'):
                    x[names['Rs']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
                x[names['Rn']] = rng.randrange(200)
            elif is_mem:
                if 'Rn' in names:
                    x[names['Rn']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
                if 'Rm' in names and names['Rm'] != 31:
                    x[names['Rm']] = rng.randrange(64)     # scaled by up to 16
            nzcv, fpcr, fpsr = rng.getrandbits(4), rng.getrandbits(32), rng.getrandbits(32)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))

            st = {'X': x, 'V': v, 'NZCV': nzcv, 'FPCR': fpcr, 'FPSR': fpsr}
            ctypes.memmove(mem, init, MEM_SIZE)
            rc, sim, sim_pc = sim_exec(capi, word, st, pc)
            try:
                out, ref_mem, ref_pc = interp_step(arch, ins, word, st, pc, base, init)
            except Fault as e:
                if rc != SIM_FAULT:
                    failures.append((ins.name, hex(word), names, f'reference faults ({e}), sim rc={rc}'))
                    break
                continue
            assert rc == 0, (ins.name, hex(word), rc)
            diff = diff_state(out, sim)
            if diff or bytes(mem) != ref_mem or sim_pc != ref_pc:
                failures.append((ins.name, hex(word), names, 'ref vs sim:', diff,
                                 f'pc ref={ref_pc:#x} sim={sim_pc:#x}',
                                 'mem differs' if bytes(mem) != ref_mem else ''))
                break
    assert not failures, '\n'.join(map(str, failures[:25])) + f'\n({len(failures)} failing)'
