"""Run C programs in the simulator generated by lira-simgen-lib and compare
their output with the same programs compiled for and run on the host.

Needs: the simulator ($LIRA_A64_SIM, default ../lira-simgen-lib/build/a64/
interpreter/interpreter), a clang that targets aarch64-linux ($LIRA_A64_CC)
and a working ld.lld ($LIRA_A64_LD). A native run for the reference output
requires an AArch64 host.
"""
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
PROGRAMS = HERE / 'programs'
SIM = Path(os.environ.get(
    'LIRA_A64_SIM',
    HERE.parents[3] / 'lira-simgen-lib' / 'build' / 'a64' / 'interpreter' / 'interpreter'))
OPT_LEVELS = ['-O0', '-O1', '-O2', '-O3', '-Os']
GUEST_FLAGS = ['--target=aarch64-linux-gnu', '-ffreestanding', '-nostdlib', '-static', '-fno-pic',
               '-mgeneral-regs-only', '-fno-stack-protector', '-mbranch-protection=none',
               '-Wl,-e,_start']


def _works(cmd):
    try:
        return subprocess.run(cmd, capture_output=True).returncode == 0
    except OSError:
        return False


def _find_cc():
    for cc in [os.environ.get('LIRA_A64_CC'), '/opt/homebrew/opt/llvm/bin/clang', shutil.which('clang')]:
        if cc and _works([cc, '--target=aarch64-linux-gnu', '-print-target-triple']):
            return cc
    return None


def _find_ld():
    cands = [os.environ.get('LIRA_A64_LD'), shutil.which('ld.lld')]
    cands += sorted(str(p) for p in Path('/opt/homebrew/opt').glob('llvm@*/bin/ld.lld'))
    for ld in cands:
        if ld and _works([ld, '--version']):
            return ld
    return None


CC, LD = _find_cc(), _find_ld()
HOST_CC = ['xcrun', 'clang'] if sys.platform == 'darwin' else ['cc']

pytestmark = [
    pytest.mark.skipif(not SIM.exists(), reason=f'{SIM} not built'),
    pytest.mark.skipif(CC is None or LD is None, reason='no aarch64 clang / ld.lld'),
    pytest.mark.skipif(platform.machine() not in ('arm64', 'aarch64'),
                       reason='reference output needs an AArch64 host'),
]


def _programs():
    return sorted(p.stem for p in PROGRAMS.glob('*.c') if not p.stem.startswith('rt_'))


@pytest.fixture(scope='module')
def host_output(tmp_path_factory):
    d = tmp_path_factory.mktemp('host')
    out = {}
    for prog in _programs():
        exe = d / prog
        subprocess.run([*HOST_CC, '-O1', '-o', exe, PROGRAMS / f'{prog}.c', PROGRAMS / 'rt_host.c'],
                       check=True)
        p = subprocess.run([exe], capture_output=True, text=True)
        out[prog] = (p.stdout, p.returncode)
    return out


def guest_flags(prog):
    """Extra flags of a program's guest build: a `guest-flags:` line in it."""
    m = re.search(r'guest-flags:(.*)', (PROGRAMS / f'{prog}.c').read_text())
    return m.group(1).split() if m else []


@pytest.mark.parametrize('opt', OPT_LEVELS)
@pytest.mark.parametrize('prog', _programs())
def test_program(prog, opt, host_output, tmp_path):
    elf = tmp_path / f'{prog}.elf'
    subprocess.run([CC, opt, *GUEST_FLAGS, *guest_flags(prog), f'--ld-path={LD}', '-o', elf,
                    PROGRAMS / f'{prog}.c', PROGRAMS / 'rt_guest.c'], check=True)
    p = subprocess.run([SIM, '--propagate-exit', '-q', elf], capture_output=True, text=True, timeout=600)
    stdout = ''.join(l for l in p.stdout.splitlines(keepends=True) if not l.startswith('Exiting with code'))
    assert p.stderr == '', p.stderr
    assert (stdout, p.returncode) == host_output[prog]


def test_static_instruction_coverage(tmp_path, capsys):
    """Report which base-set mnemonics the compiled programs contain."""
    objdump = Path(CC).with_name('llvm-objdump')
    if not objdump.exists():
        pytest.skip('llvm-objdump not found')
    seen = set()
    for prog in _programs():
        for opt in OPT_LEVELS:
            elf = tmp_path / f'{prog}{opt}.elf'
            subprocess.run([CC, opt, *GUEST_FLAGS, *guest_flags(prog), f'--ld-path={LD}', '-o', elf,
                            PROGRAMS / f'{prog}.c', PROGRAMS / 'rt_guest.c'], check=True)
            dis = subprocess.run([objdump, '-d', '-M', 'no-aliases', elf], capture_output=True, text=True).stdout
            for line in dis.splitlines():
                parts = line.split('\t')
                if len(parts) >= 2 and ':' in parts[0] and 'file format' not in line:
                    seen.add(parts[1].split('.')[0].strip())
    with capsys.disabled():
        print(f'\n{len(seen)} distinct mnemonics in test programs: {" ".join(sorted(seen))}')
