"""Verify the simulator generated by lira-simgen-lib from aarch64.yaml.

Uses the single-instruction C API library built by
    cmake --build <build> --target a64-capi      (ARCH_TARGET=AArch64)
located via $LIRA_A64_CAPI (default: ../lira-simgen-lib/build/a64/...).

* decoder: every sampled valid word decodes to its own opcode, and words that
  no encoding accepts are rejected;
* generated C++ vs. the host CPU (same cases as test_semantics_hw);
* generated C++ vs. the reference interpreter on all encodings with fully
  random fields (register 31 = SP/XZR, branches, literal loads included).
"""
import ctypes
import os
import platform
import random
import sys
from pathlib import Path

import pytest

from .conftest import sample_operands
from .test_semantics_hw import (MEM_BASE_OFF, MEM_SIZE, STATES_PER_CASE, build_cases,
                                interp_step, random_state, run_hw)

DEFAULT = Path(__file__).resolve().parents[4] / 'lira-simgen-lib' / 'build' / 'a64' / \
    'interpreter' / ('liba64-capi.dylib' if sys.platform == 'darwin' else 'liba64-capi.so')
CAPI = Path(os.environ.get('LIRA_A64_CAPI', DEFAULT))
# The description the simulator was generated from (may lag behind aarch64.yaml)
SIM_YAML = Path(os.environ.get('LIRA_A64_SIM_YAML',
                               DEFAULT.parents[3] / 'data' / 'AArch64' / 'aarch64.yaml'))

pytestmark = pytest.mark.skipif(not (CAPI.exists() and SIM_YAML.exists()),
                                reason=f'{CAPI} or {SIM_YAML} not found')

U64P = ctypes.POINTER(ctypes.c_uint64)


@pytest.fixture(scope='module')
def sim_arch():
    from python.lira.arch_ser_yaml import read_arch
    return read_arch(SIM_YAML)


@pytest.fixture(scope='module')
def sim_machine(sim_arch):
    from .lira_interp import Machine
    return Machine(sim_arch)


@pytest.fixture(scope='module')
def sim_cases(sim_arch, tmp_path_factory):
    """Hardware cases for the instructions of the simulated description."""
    return build_cases(sim_arch, tmp_path_factory.mktemp('hw'))


@pytest.fixture(scope='module')
def capi():
    lib = ctypes.CDLL(str(CAPI))
    lib.lira_a64_exec.argtypes = [ctypes.c_uint32, U64P, U64P, U64P, U64P, U64P]
    lib.lira_a64_decode.argtypes = [ctypes.c_uint32]
    return lib


def sim_step(capi, word, x, nzcv, fpcr, fpsr, pc):
    """Run one word in the generated simulator: (x, nzcv, fpcr, fpsr, pc)."""
    xs = (ctypes.c_uint64 * 32)(*x)
    regs = [ctypes.c_uint64(v) for v in (nzcv, fpcr, fpsr, pc)]
    assert capi.lira_a64_exec(word, xs, *map(ctypes.byref, regs)) == 0, hex(word)
    return [list(xs)] + [r.value for r in regs]


def test_decoder(sim_arch, sim_machine, capi):
    rng = random.Random(21)
    arch, machine = sim_arch, sim_machine
    for idx, ins in enumerate(arch.instructions):
        for _ in range(30):
            word = machine.encode(ins, sample_operands(machine, ins, rng))
            assert capi.lira_a64_decode(word) == idx, (ins.name, hex(word))
    rejected = 0
    for _ in range(20000):
        word = rng.getrandbits(32)
        if not any(machine.valid_word(i, word) for i in arch.instructions):
            assert capi.lira_a64_decode(word) == -1, hex(word)
            rejected += 1
    assert rejected > 1000


@pytest.mark.skipif(platform.machine() not in ('arm64', 'aarch64'), reason='needs an AArch64 host')
def test_simgen_matches_hardware(sim_arch, sim_cases, capi):
    """X registers, NZCV, FPCR, FPSR and memory of the generated C++ vs. the host CPU."""
    rng = random.Random(11)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for fn, ins, ops, word in sim_cases:
        for _ in range(STATES_PER_CASE):
            st = random_state(rng, ins, ops, base)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))
            ctypes.memmove(mem, init, MEM_SIZE)
            hw_out, pc = run_hw(fn, st)
            hw = (hw_out['X'], hw_out['NZCV'], hw_out['FPCR'], hw_out['FPSR'], bytes(mem))
            ctypes.memmove(mem, init, MEM_SIZE)
            x, f, fpcr, fpsr, _ = sim_step(capi, word, st['X'] + [0] * 24, st['NZCV'],
                                           st['FPCR'], st['FPSR'], pc)
            got = (x[:8], f, fpcr, fpsr, bytes(mem))
            if got != hw:
                failures.append((ins.name, hex(word), [hex(r) for r in st['X']],
                                 'hw', [hex(r) for r in hw[0]], *map(hex, hw[1:4]),
                                 'sim', [hex(r) for r in got[0]], *map(hex, got[1:4])))
                break
    assert not failures, '\n'.join(map(str, failures[:20])) + f'\n({len(failures)} failing)'


def _pick(machine, ins, rng):
    fixed = {}
    if '_ldst' in ins.name and 'Rm' in ins.operand_names:
        rn = rng.randrange(32)
        fixed['Rn'] = rn
        fixed['Rm'] = rng.choice([r for r in range(32) if r != rn])
    if 'imm12' in ins.operand_names and '_ldst' in ins.name:
        fixed['imm12'] = rng.randrange(256)          # scaled offset stays in the buffer
    if 'loadlit' in ins.name:
        fixed['imm19'] = rng.randrange(-512, 512) & ((1 << 19) - 1)
    return sample_operands(machine, ins, rng, fixed)


def test_simgen_matches_interpreter(sim_arch, sim_machine, capi):
    arch, machine = sim_arch, sim_machine
    rng = random.Random(5)
    mem = (ctypes.c_uint8 * MEM_SIZE)()
    base = ctypes.addressof(mem)
    failures = []
    for ins in arch.instructions:
        if ins.name.startswith('SVC_'):                 # effect defined by the runtime
            continue
        is_mem = '_ldst' in ins.name or 'loadlit' in ins.name
        for _ in range(40):
            ops = _pick(machine, ins, rng)
            word = machine.encode(ins, ops)
            names = dict(zip(ins.operand_names, ops))
            x = [rng.getrandbits(64) if rng.random() < 0.7 else rng.choice([0, 1, (1 << 64) - 1, 1 << 63])
                 for _ in range(32)]
            pc = base + MEM_BASE_OFF if is_mem else rng.getrandbits(62) << 2
            if is_mem:
                if 'Rn' in names:
                    x[names['Rn']] = base + MEM_BASE_OFF + rng.randrange(-256, 256)
                if 'Rm' in names and names['Rm'] != 31:
                    x[names['Rm']] = rng.randrange(256)
            nzcv, fpcr, fpsr = rng.getrandbits(4), rng.getrandbits(32), rng.getrandbits(32)
            init = bytes(rng.getrandbits(8) for _ in range(MEM_SIZE))

            st = {'X': x, 'V': [], 'NZCV': nzcv, 'FPCR': fpcr, 'FPSR': fpsr}
            out, ref_mem, ref_pc = interp_step(arch, ins, word, st, pc, base, init)
            ref = (out['X'], out['NZCV'], out['FPCR'], out['FPSR'], ref_mem, ref_pc)
            ctypes.memmove(mem, init, MEM_SIZE)
            sx, sf, sfpcr, sfpsr, spc = sim_step(capi, word, x, nzcv, fpcr, fpsr, pc)
            got = (sx, sf, sfpcr, sfpsr, bytes(mem), spc)
            if got != ref:
                diff = [f'x{i}: ref={ref[0][i]:#x} sim={sx[i]:#x}' for i in range(32) if ref[0][i] != sx[i]]
                failures.append((ins.name, hex(word), names, diff,
                                 f'nzcv ref={ref[1]} sim={sf}', f'fpcr ref={ref[2]:#x} sim={sfpcr:#x}',
                                 f'fpsr ref={ref[3]:#x} sim={sfpsr:#x}', f'pc ref={ref[5]:#x} sim={spc:#x}',
                                 'mem differs' if got[4] != ref[4] else ''))
                break
    assert not failures, '\n'.join(map(str, failures[:25])) + f'\n({len(failures)} failing)'
