"""Run valgrind's arm64 instruction tests (none/tests/arm64) in the simulator
generated by lira-simgen-lib.

Each test executes instructions from inline asm and prints the result
registers, flags and FPSR. The reference is either valgrind's .stdout.exp
(recorded on hardware) or the same source run natively on an AArch64 host.

Needs a valgrind checkout ($VALGRIND_SRC, default ../valgrind next to LIRA);
only none/tests/arm64 is used:

    git clone --depth 1 --filter=blob:none --sparse https://sourceware.org/git/valgrind.git
    git -C valgrind sparse-checkout set none/tests/arm64

The sources are GPL-2 and are not copied here. The guest build uses the libc in
valgrind/. An instruction is runnable when it assembles (llvm-mc) and decodes
in the description the simulator was generated from:

* a program compared with .stdout.exp must be runnable entirely (else skip);
* a program compared with the native run keeps its runnable parts: the
  other test_* functions get empty bodies (after preprocessing, as the tests
  are generated by macros), and memory_test drops the other test cases.
"""
import ctypes
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

import pytest

from .test_programs import CC, GUEST_FLAGS, HOST_CC, LD, SIM
from .test_simgen import CAPI

HERE = Path(__file__).resolve().parent
RT = HERE / 'valgrind'
VALGRIND = Path(os.environ.get('VALGRIND_SRC', HERE.parents[3] / 'valgrind'))
TESTS = VALGRIND / 'none' / 'tests' / 'arm64'

AARCH64_HOST = platform.machine() in ('arm64', 'aarch64')

pytestmark = [
    pytest.mark.skipif(not SIM.exists(), reason=f'{SIM} not built'),
    pytest.mark.skipif(CC is None or LD is None, reason='no aarch64 clang / ld.lld'),
    pytest.mark.skipif(not TESTS.is_dir(), reason=f'no valgrind checkout at {VALGRIND} (set $VALGRIND_SRC)'),
    pytest.mark.skipif(not CAPI.exists(), reason=f'{CAPI} not built'),
]


# -- Source adjustments ---------------------------------------------------------

def cast_operands(src: str) -> str:
    """The TESTINST macros pass int literals to "r" operands used as X registers,
    whose upper half is then undefined; make them 64-bit."""
    return re.sub(r'"r" \((R[A-Z]+val)\)', r'"r" ((ULong)(\1))', src)


# -- Which instructions the simulator runs ------------------------------------------

MC_ATTRS = '+v8.9a,+fullfp16,+fp16fml,+aes,+sha2,+sha3,+sm4,+i8mm,+dotprod,+rdm,+crc,+lse'


def _byte(b: str) -> int:
    """A byte of llvm-mc's encoding; fixup bits (label references) read as 0."""
    b = b.strip()
    if b.startswith('0x'):
        return int(b, 16)
    return int(re.sub(r'[^01]', '0', b[2:] if b.startswith('0b') else '0'), 2)


def assemble(texts):
    """Encode each asm text (statements separated by ';' or newlines) with
    llvm-mc: the list of words per text, None where a statement is rejected."""
    mc = Path(CC).with_name('llvm-mc')
    lines, owner = [], []           # asm lines; the text each line belongs to
    for i, text in enumerate(texts):
        stmts = [st.strip() for st in re.split(r'[;\n]', text) if st.strip()]
        lines += [f'.ascii "@{i}"'] + stmts
        owner += [i] * (len(stmts) + 1)
    p = subprocess.run([mc, '-triple=aarch64', f'-mattr={MC_ATTRS}', '--show-encoding'],
                       input='\n'.join(lines), capture_output=True, text=True)
    bad = {owner[int(n) - 1] for n in re.findall(r'^<stdin>:(\d+):\d+: error', p.stderr, re.M)}
    words, cur = [[] for _ in texts], None
    for line in p.stdout.splitlines():
        if m := re.search(r'\.ascii\s+"@(\d+)"', line):
            cur = int(m.group(1))
        elif m := re.search(r'encoding: \[([^\]]*)\]', line):
            words[cur].append(int.from_bytes(bytes(map(_byte, m.group(1).split(','))), 'little'))
    return [None if i in bad else w for i, w in enumerate(words)]


_capi = None


def sim_decodes(word: int) -> bool:
    """The word decodes in the generated simulator (its C API decoder)."""
    global _capi
    if _capi is None:
        _capi = ctypes.CDLL(str(CAPI))
        _capi.lira_a64_decode.argtypes = [ctypes.c_uint32]
    return _capi.lira_a64_decode(word) != -1


def supported(texts):
    """For each asm text: every statement assembles and decodes in the simulator."""
    return [w is not None and all(map(sim_decodes, w)) for w in assemble(texts)]


def unsupported_statements(texts):
    """The asm statements of `texts` the simulator does not run."""
    stmts = sorted({st.strip() for t in texts for st in re.split(r'[;\n]', t) if st.strip()})
    return [st for st, ok in zip(stmts, supported(stmts)) if not ok]


# -- Inline asm of a C source ---------------------------------------------------

def _operand_reg(m) -> str:
    """A register for the asm operand %<n> (with its modifier): x10 + n."""
    n = 10 + (int(m.group(2)) if m.group(2).isdigit() else 0)
    return f'{m.group(1) or "x"}{n}'


def _literal(text: str, i: int):
    """The C string literal starting at text[i] ('"'): (value, end index)."""
    j = i + 1
    while text[j] != '"':
        j += 2 if text[j] == '\\' else 1
    return bytes(text[i + 1:j], 'utf-8').decode('unicode_escape'), j + 1


def _asm_literals(text: str):
    """For each inline asm statement: its position and the (start, end) spans
    of the string literals of its template."""
    for m in re.finditer(r'\b(?:__asm__|asm)\b\s*(?:__volatile__|volatile)?\s*\(', text):
        i, spans = m.end(), []
        while True:
            while text[i].isspace():
                i += 1
            if text[i] != '"':
                break
            _, end = _literal(text, i)
            spans.append((i, end))
            i = end
        yield m.start(), spans


def asm_templates(text: str):
    """(position, template) of every inline asm statement of preprocessed C,
    with the operands (%0, %w1, ...) replaced by registers."""
    out = []
    for pos, spans in _asm_literals(text):
        tmpl = ''.join(_literal(text, a)[0] for a, _ in spans)
        tmpl = re.sub(r'%([wxsdqbh]?)(\d+|\[\w+\])', _operand_reg, tmpl)
        out.append((pos, tmpl.replace('%%', '%')))
    return out


def darwin_asm(text: str) -> str:
    """Darwin's assembler treats ';' as a comment: separate the statements of
    the inline asm templates of preprocessed C with newlines."""
    out, last = [], 0
    for _, spans in _asm_literals(text):
        for a, b in spans:
            out += [text[last:a], text[a:b].replace(';', '\\n')]
            last = b
    return ''.join(out) + text[last:]


def _test_functions(text: str):
    """(name, body start, body end) of each test_* function defined in
    preprocessed C; the body is text[start:end] without the braces."""
    for m in re.finditer(r'\b(test_\w+)\s*\([^()]*\)\s*\{', text):
        depth, i = 1, m.end()
        while depth:
            depth += {'{': 1, '}': -1}.get(text[i], 0)
            i += 1
        yield m.group(1), m.end(), i - 1


def functions_asm(text: str):
    """Asm templates of each test_* function defined in preprocessed C."""
    templates = asm_templates(text)
    return {name: [t for pos, t in templates if start <= pos < end]
            for name, start, end in _test_functions(text)}


def stub_functions(text: str, names) -> str:
    """Preprocessed C with the bodies of the named test functions emptied."""
    out, last = [], 0
    for name, start, end in _test_functions(text):
        if name in names:
            out.append(text[last:start])
            last = end
    return ''.join(out) + text[last:]


def preprocess(src: Path, flags) -> str:
    p = subprocess.run([CC, '-E', '-P', *guest_cflags(), f'-I{RT / "include"}', f'-I{TESTS}',
                        *flags, str(src)], capture_output=True, text=True, check=True)
    return p.stdout


def preprocess_host(src: Path, flags) -> str:
    p = subprocess.run([*HOST_CC, '-E', '-P', f'-I{RT / "host"}', f'-I{TESTS}', *flags, str(src)],
                       capture_output=True, text=True, check=True)
    return darwin_asm(p.stdout) if sys.platform == 'darwin' else p.stdout


# -- Filters of programs compared with the native run ---------------------------------

_CASE = re.compile(r'^\s*(MEM_TEST|TESTINST\w*)\s*\(\s*("(?:[^"\\]|\\.)*")')


def supported_cases(src: str) -> str:
    """memory_test.c with the cases the simulator runs."""
    lines = src.split('\n')
    cases, i = [], 0                # (first line, last line, asm text)
    while i < len(lines):
        m = _CASE.match(lines[i])
        if m:
            j = i
            while not re.search(r'\)\s*;?\s*$', lines[j]):
                j += 1
            cases.append((i, j, m.group(2)[1:-1]))
            i = j
        i += 1
    drop = set()
    for (first, last, _), ok in zip(cases, supported([c[2] for c in cases])):
        if not ok:
            drop.update(range(first, last + 1))
    out = []
    for n, line in enumerate(lines):
        if n in drop:
            continue
        # AREA_MID rounds into `area` by address; pin its alignment so the
        # data read does not depend on the stack layout.
        out.append(line.replace('unsigned char area[512];', 'unsigned char area[512] __attribute__((aligned(16)));'))
    return '\n'.join(out)


def unsupported_functions(guest_text: str):
    """The test functions of preprocessed C the simulator cannot run, and the
    number of test functions."""
    funcs = functions_asm(guest_text)
    names = list(funcs)
    ok = supported(['\n'.join(funcs[n]) for n in names])
    return {n for n, good in zip(names, ok) if not good}, len(names)


# -- Build and run --------------------------------------------------------------

def guest_cflags():
    # The tests' inline asm uses SIMD&FP registers and the harnesses use
    # floating point; the compiler must not vectorize on its own
    # (-mno-implicit-float instead of -mgeneral-regs-only).
    return [f for f in GUEST_FLAGS if f != '-mgeneral-regs-only'] + ['-mno-implicit-float']


# The test program is built at -O0 as in valgrind; the shared harness (simd.c)
# at -O1, where int-to-float conversions use SCVTF from a general register
# (the SIMD&FP-register form is not in the description).
HARNESS_OPT = '-O1'


def build_guest(srcs, elf: Path, flags):
    cc = [CC, *guest_cflags(), '-march=armv8-a+crc', '-fno-builtin', '-nostdlibinc',
          f'-I{RT / "include"}', f'-I{TESTS}', '-w', *flags]
    objs = []
    for src in srcs[1:]:
        objs.append(src.with_suffix('.guest.o'))
        subprocess.run([*cc, HARNESS_OPT, '-c', '-o', objs[-1], src], check=True)
    subprocess.run([*cc, '-O0', f'--ld-path={LD}', '-o', elf, srcs[0], *objs, RT / 'rt.c'], check=True)


def unsupported_code(elf: Path):
    """Disassembly of the words of the ELF's code the simulator cannot
    decode (e.g. compiler-generated SIMD&FP instructions of the harness)."""
    bin_ = elf.with_suffix('.text')
    subprocess.run([Path(CC).with_name('llvm-objcopy'), '-O', 'binary', '--only-section=.text',
                    elf, bin_], check=True)
    data = bin_.read_bytes()
    words = {int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data) - 3, 4)}
    bad = sorted(w for w in words if not sim_decodes(w))
    if not bad:
        return []
    p = subprocess.run([Path(CC).with_name('llvm-mc'), '--disassemble', '-triple=aarch64',
                        f'-mattr={MC_ATTRS}'],
                       input='\n'.join(' '.join(f'0x{(w >> (8 * i)) & 0xff:02x}' for i in range(4))
                                       for w in bad), capture_output=True, text=True)
    return sorted({l.split('\t')[1] for l in p.stdout.splitlines() if l.startswith('\t')})


def run_guest(elf: Path) -> str:
    missing = unsupported_code(elf)
    if missing:
        pytest.skip(f'the code uses instructions not in the simulator yet: {missing[:8]}')
    p = subprocess.run([SIM, '--propagate-exit', '-q', elf], capture_output=True, text=True, timeout=1200)
    assert p.stderr == '', p.stderr
    assert p.returncode == 0
    return ''.join(l for l in p.stdout.splitlines(keepends=True) if not l.startswith('Exiting with code'))


def run_host(srcs, exe: Path, flags) -> str:
    cc = [*HOST_CC, '-w', f'-I{RT / "host"}', f'-I{TESTS}', *flags]
    objs = []
    for src in srcs[1:]:
        objs.append(src.with_suffix('.host.o'))
        subprocess.run([*cc, HARNESS_OPT, '-c', '-o', objs[-1], src], check=True)
    subprocess.run([*cc, '-O0', '-o', exe, srcs[0], *objs], check=True)
    p = subprocess.run([exe], capture_output=True, text=True, timeout=1200)
    assert p.returncode == 0
    return p.stdout


def _prepare(prog, extra, tmp_path):
    """Adjusted copies of the program and its extra sources in tmp_path."""
    srcs = []
    for name in [prog] + extra:
        src = tmp_path / f'{name}.c'
        src.write_text(cast_operands((TESTS / f'{name}.c').read_text()))
        srcs.append(src)
    return srcs


# program, expected output, extra sources, flags (as in valgrind's Makefile.am)
EXPECTED = [
    ('integer', 'integer', [], ['-DTEST_BFM=0']),
    ('crc32', 'crc32', [], []),
    ('atomics_v81', 'atomics_v81', [], ['-march=armv8.1-a']),
    ('ldxp_stxp', 'ldxp_stxp_basisimpl', [], []),
    ('fmadd_sub', 'fmadd_sub', [], []),
    ('cvtf_imm', 'cvtf_imm', [], []),
]


@pytest.mark.parametrize('prog, expected, extra, flags', EXPECTED, ids=[e[0] for e in EXPECTED])
def test_expected(prog, expected, extra, flags, tmp_path):
    """Compare with valgrind's expected output, recorded on hardware."""
    srcs = _prepare(prog, extra, tmp_path)
    missing = unsupported_statements(
        [t for src in srcs for _, t in asm_templates(preprocess(src, flags))])
    if missing:
        pytest.skip(f'not in the simulator yet: {missing[:8]}{" ..." if len(missing) > 8 else ""}')
    build_guest(srcs, tmp_path / f'{prog}.elf', flags)
    assert run_guest(tmp_path / f'{prog}.elf') == (TESTS / f'{expected}.stdout.exp').read_text()


# program, extra sources, flags, filter of the runnable parts
HOST = [
    ('integer', [], ['-DTEST_BFM=1'], None),       # + SBFM/UBFM/BFM, no .stdout.exp
    ('memory_test', [], [], 'cases'),
    ('fp_and_simd', ['simd'], [], 'functions'),
    ('fp_and_simd_v82', ['simd'], ['-march=armv8.2-a+fp16+crypto'], 'functions'),
    ('simd_v81', [], ['-march=armv8.1-a+crypto'], 'functions'),
    ('simd_dotprod', [], ['-march=armv8.2-a+dotprod'], 'functions'),
    ('v8crypto', ['simd'], ['-march=armv8-a+crypto'], 'functions'),
    ('sha512_v82', ['simd'], ['-march=armv8.2-a+sha3'], 'functions'),
]


@pytest.mark.skipif(not AARCH64_HOST, reason='reference output needs an AArch64 host')
@pytest.mark.parametrize('prog, extra, flags, keep', HOST, ids=[h[0] for h in HOST])
def test_host(prog, extra, flags, keep, tmp_path):
    """Compare the runnable parts with the same source run natively."""
    srcs = _prepare(prog, extra, tmp_path)
    main = srcs[0]
    if keep == 'cases':
        main.write_text(supported_cases(main.read_text()))
    skip = set()
    guest = list(srcs)
    if keep == 'functions':
        guest_text = preprocess(main, flags)
        skip, total = unsupported_functions(guest_text)
        if len(skip) == total:
            pytest.skip('no test function the simulator runs yet')
        guest[0] = tmp_path / f'{prog}.guest.i.c'
        guest[0].write_text(stub_functions(guest_text, skip))
    host = []
    for src in srcs:                 # preprocessed: see darwin_asm
        host.append(tmp_path / f'{src.stem}.host.i.c')
        host[-1].write_text(stub_functions(preprocess_host(src, flags), skip))
    build_guest(guest, tmp_path / f'{prog}.elf', flags)
    assert run_guest(tmp_path / f'{prog}.elf') == run_host(host, tmp_path / prog, flags)
